### ISSUE TITLE
Application Error - Heroku App Crashing

### ISSUE THREAD

**Issue by coreypollock** [rauchg/slackin#112]
Getting this error: http://hashtaggaming.herokuapp.com
Also seeing it here: http://sass-chat.herokuapp.com/

Message on website :

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

Error log:

In context:
'2015-10-09 15:06:34.535 115 <190>1 2015-10-09T15:05:27.410298+00:00 app web.1 - - /app/node/slack.js:42
2015-10-09 15:06:34.535 158 <190>1 2015-10-09T15:05:27.410303+00:00 app web.1 - -           (res.body.channels || []).forEach(function (channel) {
2015-10-09 15:06:34.535 109 <190>1 2015-10-09T15:05:27.410304+00:00 app web.1 - -               ^
2015-10-09 15:06:34.535 94 <190>1 2015-10-09T15:05:27.410306+00:00 app web.1 - -
2015-10-09 15:06:34.535 145 <190>1 2015-10-09T15:05:27.410307+00:00 app web.1 - - TypeError: Cannot read property 'body' of undefined
   at /app/node/slack.js:42:15
   at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
   at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
   at emitOne (events.js:77:13)
   at ClientRequest.emit (events.js:169:7)
   at TLSSocket.socketErrorListener (_http_client.js:259:9)
   at emitOne (events.js:77:13)
   at TLSSocket.emit (events.js:169:7)
   at emitErrorNT (net.js:1250:8)
   at doNTCallback2 (node.js:430:9)
2015-10-09 15:06:47.449 134 <45>1 2015-10-09T15:05:23.692822+00:00 heroku web.1 - - State changed from crashed to starting
2015-10-09 16:12:38.485 299 <158>1 2015-10-09T16:11:30.965286+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/" host=hashtaggaming.herokuapp.com request_id=dd299d18-875d-4dc2-920b-203bdbf322dc fwd="199.116.169.254" dyno= connect= service= status=503 bytes=
2015-10-09 16:12:44.085 309 <158>1 2015-10-09T16:11:36.621248+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hashtaggaming.herokuapp.com request_id=8dc6b7cf-ee0d-4292-bd07-74020610f9e2 fwd="134.134.139.76" dyno= connect= service= status=503 bytes=
2015-10-09 16:13:10.700 296 <158>1 2015-10-09T16:12:03.241536+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/" host=hashtaggaming.herokuapp.com request_id=e37f782b-fd2f-4f4c-8c17-c678652ffd68 fwd="192.55.55.41" dyno= connect= service= status=503 bytes=
2015-10-09 20:13:34.785 310 <158>1 2015-10-09T20:12:26.835848+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hashtaggaming.herokuapp.com request_id=78329d07-3dca-489c-b8a3-26a03fd2ba03 fwd="207.194.226.213" dyno= connect= service= status=503 bytes=
2015-10-09 21:26:20.583 298 <158>1 2015-10-09T21:25:12.591934+00:00 heroku router - - at=error code=H10 desc="App crashed" method=GET path="/" host=hashtaggaming.herokuapp.com request_id=44444e04-216c-487c-bedc-78c70cd210b0 fwd="216.239.45.130" dyno= connect= service= status=503 bytes='

**Comment by jwood803** [comment]
I get something similar:

```
2015-10-10T01:17:58.375229+00:00 app[web.1]: Sat Oct 10 2015 01:17:58 GMT+0000 (UTC) – online 9, total 176 
2015-10-10T01:17:58.374373+00:00 app[web.1]: Sat Oct 10 2015 01:17:58 GMT+0000 (UTC) – ready
2015-10-10T01:17:59.447112+00:00 app[web.1]: /app/node/slack.js:70
2015-10-10T01:17:59.447119+00:00 app[web.1]:                          ^
2015-10-10T01:17:59.447125+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2015-10-10T01:17:59.447121+00:00 app[web.1]: TypeError: Cannot read property 'forEach' of undefined
2015-10-10T01:17:59.447118+00:00 app[web.1]:         res.body.channels.forEach(function (channel) {
2015-10-10T01:17:59.447122+00:00 app[web.1]:     at SlackData.onres (/app/node/slack.js:70:26)
2015-10-10T01:17:59.447132+00:00 app[web.1]:     at IncomingMessage.emit (events.js:129:20)
2015-10-10T01:17:59.381954+00:00 app[web.1]: Sat Oct 10 2015 01:17:59 GMT+0000 (UTC) – fetching
2015-10-10T01:17:59.447124+00:00 app[web.1]:     at /app/node/slack.js:41:17
2015-10-10T01:17:59.447130+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:938:12)
2015-10-10T01:17:59.447133+00:00 app[web.1]:     at _stream_readable.js:908:16
2015-10-10T01:17:59.447129+00:00 app[web.1]:     at Request.emit (events.js:107:17)
2015-10-10T01:17:59.447127+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/superagent/lib/node/index.js:135:10)
2015-10-10T01:17:59.447135+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-10-10T01:18:00.322476+00:00 heroku[web.1]: Process exited with status 1
2015-10-10T01:18:00.339405+00:00 heroku[web.1]: State changed from up to crashed
```

Though my error may have already been fixed since I last deployed to Heroku.

**Comment by amatecha** [comment]
Yeah, I'm getting this too.  Maybe Slack API changed?

```
←[36m2015-10-11T22:45:00.035267+00:00 app[web.1]:←[0m Sun Oct 11 2015 22:45:00 GMT+0000 (UTC) ��� fetching
←[36m2015-10-11T22:45:00.098315+00:00 app[web.1]:←[0m /app/node/slack.js:70
←[36m2015-10-11T22:45:00.098320+00:00 app[web.1]:←[0m         res.body.channels.forEach(function (channel) {
←[36m2015-10-11T22:45:00.098322+00:00 app[web.1]:←[0m                          ^
←[36m2015-10-11T22:45:00.098323+00:00 app[web.1]:←[0m TypeError: Cannot read property 'forEach' of undefined
←[36m2015-10-11T22:45:00.098324+00:00 app[web.1]:←[0m     at SlackData.onres (/app/node/slack.js:70:26)
←[36m2015-10-11T22:45:00.098326+00:00 app[web.1]:←[0m     at /app/node/slack.js:41:17
←[36m2015-10-11T22:45:00.098327+00:00 app[web.1]:←[0m     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
←[36m2015-10-11T22:45:00.098329+00:00 app[web.1]:←[0m     at Request.<anonymous> (/app/node_modules/superagent/lib/node/index.js:135:10)
←[36m2015-10-11T22:45:00.098330+00:00 app[web.1]:←[0m     at Request.emit (events.js:107:17)
←[36m2015-10-11T22:45:00.098334+00:00 app[web.1]:←[0m     at _stream_readable.js:908:16
←[36m2015-10-11T22:45:00.098332+00:00 app[web.1]:←[0m     at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/index.js:938:12)
←[36m2015-10-11T22:45:00.098333+00:00 app[web.1]:←[0m     at IncomingMessage.emit (events.js:129:20)
←[36m2015-10-11T22:45:00.098335+00:00 app[web.1]:←[0m     at process._tickCallback (node.js:355:11)
```

**Comment by amatecha** [comment]
I updated to Slackin 0.6.0 and it doesn't seem to be crashing now (fingers crossed).  @coreypollock @jwood803 , have you tried updating to the latest version of Slackin?   I was running 0.5.0 so there were a lot of changes my instance didn't have  ;)

**Comment by coreypollock** [comment]
Booyah @amatecha ! Just redeployed Slackin 0.6.0 (though I am pretty sure I had some that before) and we seem to be working well now. Thanks :)

**Comment by jwood803** [comment]
I was thinking that it would just need to be redeployed. @coreypollock did you just hit the "Deploy to Heroku" button again and go through all that or did you do something else?

**Comment by coreypollock** [comment]
@jwood803 I simply deleted the instance on Heroku, and redeployed through the Slackin Github. Not sure why it didn't work the first time :s

**Comment by jwood803** [comment]
Thanks @coreypollock! That's what I just did and all looks good now!

**Comment by burtherman** [comment]
Getting the same error -- I deployed using the button directly from Github. Any ideas what's going on?

**Comment by burtherman** [comment]
Here's my log: 

2015-10-15T19:10:02.323291+00:00 app[web.1]: Thu Oct 15 2015 19:10:02 GMT+0000 (UTC) – fetching
2015-10-15T19:10:02.381990+00:00 app[web.1]: /app/node/slack.js:48
2015-10-15T19:10:02.381994+00:00 app[web.1]:           var team = res.body.team;
2015-10-15T19:10:02.381994+00:00 app[web.1]:                         ^
2015-10-15T19:10:02.381995+00:00 app[web.1]: 
2015-10-15T19:10:02.381997+00:00 app[web.1]:     at /app/node/slack.js:48:25
2015-10-15T19:10:02.381996+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined
2015-10-15T19:10:02.381999+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-10-15T19:10:02.381998+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2015-10-15T19:10:02.381999+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2015-10-15T19:10:02.382000+00:00 app[web.1]:     at ClientRequest.emit (events.js:169:7)
2015-10-15T19:10:02.382001+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-10-15T19:10:02.382001+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:259:9)
2015-10-15T19:10:02.382002+00:00 app[web.1]:     at TLSSocket.emit (events.js:169:7)
2015-10-15T19:10:02.382003+00:00 app[web.1]:     at emitErrorNT (net.js:1253:8)
2015-10-15T19:10:02.382004+00:00 app[web.1]:     at doNTCallback2 (node.js:439:9)
2015-10-15T19:10:02.357942+00:00 app[web.1]: Thu Oct 15 2015 19:10:02 GMT+0000 (UTC) – listening on 0.0.0.0:15857
2015-10-15T19:10:03.140332+00:00 heroku[web.1]: Process exited with status 1
2015-10-15T19:10:03.152446+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by maxbhenry** [comment]
I have the same problem on Heroku, I deleted the app, redeployed it and we still have the same problem...

I checked with Heroku people and they told me:

Looking at your app logs with the heroku logs command, I see your app is crashed due to an exception at boot preventing the process from staying up.
2015-10-15T09:19:17.023294+00:00 app[web.1]: Thu Oct 15 2015 09:19:17 GMT+0000 (UTC) – listening on 0.0.0.0:15771
2015-10-15T09:19:17.074439+00:00 app[web.1]: /app/node/slack.js:49
2015-10-15T09:19:17.074441+00:00 app[web.1]: _this.org.name = team.name;
2015-10-15T09:19:17.074442+00:00 app[web.1]: ^
2015-10-15T09:19:17.074443+00:00 app[web.1]:
2015-10-15T09:19:17.074444+00:00 app[web.1]: TypeError: Cannot read property 'name' of undefined
2015-10-15T09:19:17.008657+00:00 app[web.1]: Thu Oct 15 2015 09:19:17 GMT+0000 (UTC) – fetching
2015-10-15T09:19:17.071682+00:00 app[web.1]: Thu Oct 15 2015 09:19:17 GMT+0000 (UTC) – Error: Invalid Slack response: 200
2015-10-15T09:19:17.071687+00:00 app[web.1]: at /app/node/slack.js:61:17
2015-10-15T09:19:17.071686+00:00 app[web.1]: at SlackData.onres (/app/node/slack.js:89:22)
2015-10-15T09:19:17.074445+00:00 app[web.1]: at /app/node/slack.js:49:32
2015-10-15T09:19:17.074445+00:00 app[web.1]: at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2015-10-15T09:19:17.074446+00:00 app[web.1]: at Request. (/app/node_modules/superagent/lib/node/index.js:135:10)
2015-10-15T09:19:17.071688+00:00 app[web.1]: at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2015-10-15T09:19:17.071689+00:00 app[web.1]: at Request. (/app/node_modules/superagent/lib/node/index.js:135:10)
2015-10-15T09:19:17.071690+00:00 app[web.1]: at emitOne (events.js:77:13)
2015-10-15T09:19:17.071692+00:00 app[web.1]: at emitNone (events.js:72:20)

whats is happening? has slack changed something to make it more difficult for people to sign up?

**Comment by ebel** [comment]
same as @maxbhenry for me. redeploy did not help. Any ideas?!

**Comment by maxbhenry** [comment]
Still not working and no response or feedback from the developer... what is happening?

**Comment by jeanleonino** [comment]
Looks like lots of groups are having this problem.

**Comment by maxbhenry** [comment]
Yes, looks like the problem is widespread now and hopefully the developer is aware of it and trying to fix the problem..

**Comment by jeanleonino** [comment]
@maxbhenry looks like @rauchg is not active on Github anymore... Tried to talk to him on Twitter

**Comment by rauchg** [comment]
I'm taking a look at this!

**Comment by burtherman** [comment]
@rauchg Thanks! (I found it a bit hard to believe that you were not active on Github :) )

**Comment by maxbhenry** [comment]
Guillermo (@rauchg), any updates on the bug that is affecting a number of users?

**Comment by rauchg** [comment]
I really can't reproduce the issue. That said, I did a more in-depth review of the patch Slack submitted to us, and it does not seem to do any sort of error handling (`err` is ignored altogether in the callbacks). Furthermore, the requests are not made in order, so it's possible that the `fetch` event gets emitted before the team and channels information is retrieved.

cc @ssandler

**Comment by tomfulton** [comment]
FYI - upgrading (by deleting/redeploying) seems to have fixed the issue for me!

**Comment by amatecha** [comment]
I updated mine by forking the repo and attaching my heroku account to my github repo and deploying from there :thumbsup:

**Comment by burtherman** [comment]
@amatecha I just tried that too -- and it worked! Thanks for the tip!

**Comment by maxbhenry** [comment]
it still does not work for me... I deleted the app and redeployed it but still get the same error when opening our page:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details.

In the Slack's subdomain, do you just write your name (before ".slack.com") or do you enter the full domain xxx.slack.com?

is there any other parameter I need to check within Slack?

Thanks for your help.

**Comment by burtherman** [comment]
@maxbhenry Actually you're right -- I also changed that parameter to just the subdomain without the ".slack.com" added and that worked. I'll submit a pull request to make that clearer on the docs

**Comment by maxbhenry** [comment]
OK, great, it works again, thanks for the support!

**Comment by bntzio** [comment]
Great, it works! 
---
Does anyone know what to do after setting up the heroku app? I go to myapp.herokuapp.com and it shows an application error, do I need to do something else to get this working?  Thanks.

**Comment by lambtron** [comment]
I was experiencing the same thing. Deleted my heroku app and went through the process via the Deploy via Heroku button. Now it works!

**Comment by mxui** [comment]
I have met this problem too.At last  I figured out that it's my config problem.

The **SLACK_SUBDOMAIN** Config Variables should be the leading part of your team-url.
But I set it to  **masterchinese.slack.com** which should be **masterchinese**.

![screenshot from 2015-11-06 14 40 46](https://cloud.githubusercontent.com/assets/6848366/10991015/699ed1b2-8494-11e5-88ef-aa017a206a07.png)

The above explanation is misleading.

**Comment by rauchg** [comment]
Clarifying in the README

**Comment by rauchg** [comment]
Clarified! Let me know if it makes more sense now.

**Comment by webriq** [comment]
I still ran into the bit of confusion before I figure it out. Your *Team ID* is a one word and is a subdomain of slack. Use only that and not the whole *https://teamid.slack.com*. Thanks
